name: Build Executables and Host on GitHub Releases

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-linux:
    name: Build Linux Binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Create Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pyinstaller --clean -y --onefile --add-data="constants.py:." client.py

      - name: Archive Binary
        run: mv dist/client ./linux_binary

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-binary
          path: ./linux_binary

  build-windows:
    name: Build Windows Executable
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Create Virtual Environment
        run: |
          python -m venv venv
          venv\Scripts\activate
          venv\Scripts\pip install -r requirements.txt
          pyinstaller --clean -y --onefile --add-data="constants.py:." client.py

      - name: Archive Executable
        run: move dist\client.exe windows_binary.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: ./windows_binary.exe

  build-macos:
    name: Build macOS Binary
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Create Virtual Environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install pyinstaller

      - name: Build Binary
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pyinstaller --clean -y --onefile --add-data="constants.py:." client.py

      - name: Archive Binary
        run: mv dist/client ./linux_binary

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-binary
          path: ./macos_binary

  release:
    name: Create Release
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux Binary
        uses: actions/download-artifact@v3
        with:
          name: linux-binary
          path: ./release

      - name: Download Windows Executable
        uses: actions/download-artifact@v3
        with:
          name: windows-executable
          path: ./release

      - name: Download macOS Binary
        uses: actions/download-artifact@v3
        with:
          name: macos-binary
          path: ./release

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            ./release/linux_binary
            ./release/windows_binary.exe
            ./release/macos_binary
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.run_number }}
          name: Release v${{ github.run_number }}
          body: |
            - Built executables for Linux, Windows, and macOS platforms.
